DATABASE_NAME=api_development
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres
DATABASE_HOST=localhost:5432

DATABASE_USER=$DATABASE_USER DATABASE_PASSWORD=$DATABASE_PASSWORD DATABASE_HOST=$DATABASE_HOST DATABASE_NAME=$DATABASE_NAME SSL='/home/mike/letsencrypt/live/shintech.ninja' python3.5 app.py
